language: cpp
dist:     bionic
compiler: gcc

before_install:
  - LIBNINJAM_SOURCES_LIST=/etc/apt/sources.list.d/ninjam_ninjam.list
  - BUILD_DIR=/home/travis/build/linjam/linjam/Builds/Makefile
  - LIBNINJAM_DEPS='libogg-dev libvorbis-dev libasound2-dev libjack-dev'
  - LINJAM_DEPS='libfreetype6-dev libx11-dev libxinerama-dev libxcursor-dev
                 mesa-common-dev libasound2-dev libjack-dev freeglut3-dev
                 libxcomposite-dev libxrandr-dev libxrender-dev'
  - sudo apt-get update -qq
  - sudo apt-get install -y $LIBNINJAM_DEPS $LINJAM_DEPS git
  - git clone -b v0.7.0 https://github.com/libninjam/libninjam.git

script:
  - cd libninjam && make && sudo make install
  - cd $BUILD_DIR && make CONFIG=Release
